# Generated by Django 4.0 on 2022-04-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
